name: Kinkin Auto Runner V108

on:
  schedule:
    # Chạy vào phút thứ 0 và 30 của mỗi giờ (Ví dụ: 8:00, 8:30, 9:00...)
    - cron: '0,30 * * * *'
  workflow_dispatch: # Cho phép bấm nút "Run workflow" thủ công để test

jobs:
  run_data_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas gspread oauth2client gspread-dataframe

      - name: Run Auto Job Script
        env:
          # Nạp Key từ GitHub Secrets vào biến môi trường
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          GCP_SERVICE_ACCOUNT_1: ${{ secrets.GCP_SERVICE_ACCOUNT_1 }}
          GCP_SERVICE_ACCOUNT_2: ${{ secrets.GCP_SERVICE_ACCOUNT_2 }}
          GCP_SERVICE_ACCOUNT_3: ${{ secrets.GCP_SERVICE_ACCOUNT_3 }}
          GCP_SERVICE_ACCOUNT_4: ${{ secrets.GCP_SERVICE_ACCOUNT_4 }}
          HISTORY_SHEET_ID: ${{ secrets.HISTORY_SHEET_ID }}
        run: python auto_job.py
